#!/bin/bash

SOURCES=$(find src -type f \( -name "*.cpp" -o -name "*.hpp" \) ! -name "*autogenerated*")
INCLUDES=$(find include -type f -name "*.hpp" ! -name "*autogenerated*")

COMMAND="clang-tidy-19 $SOURCES $INCLUDES -p build"

echo $COMMAND
$COMMAND
