document
  = { document-markup-element };
document-markup-element
  = DOCUMENT-TEXT-TOKEN
  | common-markup-element;
common-markup-element
  = ESCAPE-TOKEN
  | LINE-COMMENT-TOKEN
  | BLOCK-COMMENT-TOKEN
  | directive-splice
  | expression-splice;
directive-splice
  = DIRECTIVE-SPLICE-NAME-TOKEN, [ group ], [ block ];
expression-splice
  = EXPRESSION-SPLICE-TOKEN, expression, PARENTHESIS-RIGHT-TOKEN;
identifier
  = IDENTIFIER-TOKEN;
group
  = PARENTHESIS-LEFT-TOKEN, PARENTHESIS-RIGHT-TOKEN
  | PARENTHESIS-LEFT-TOKEN, named-group-member, [ COMMA-TOKEN, [ group-member-list ] ], PARENTHESIS-RIGHT-TOKEN
  | PARENTHESIS-LEFT-TOKEN, ELLIPSIS-TOKEN, [ COMMA-TOKEN, [ group-member-list ] ], PARENTHESIS-RIGHT-TOKEN
  | PARENTHESIS-LEFT-TOKEN, positional-group-member, COMMA-TOKEN, [ group-member-list ], PARENTHESIS-RIGHT-TOKEN;
group-member-list
  = group-member, { COMMA-TOKEN, group-member }, [ COMMA-TOKEN ];
group-member
  = named-group-member
  | positional-group-member
  | ELLIPSIS-TOKEN;
named-group-member
  = member-name, EQUALS-TOKEN, expression;
positional-group-member
  = expression;
member-name
  = identifier
  | string-literal;
expression
  = logical-or-expression;
logical-or-expression
  = logical-and-expression
  | logical-or-expression, LOGICAL-OR-TOKEN, logical-and-expression;
logical-and-expression
  = equality-expression
  | logical-and-expression, LOGICAL-AND-TOKEN, equality-expression;
equality-expression
  = relational-expression
  | equality-expression, EQUALS-TOKEN, relational-expression
  | equality-expression, NOT-EQUALS-TOKEN, relational-expression;
relational-expression
  = additive-expression
  | relational-expression, LESS-THAN-TOKEN, additive-expression
  | relational-expression, GREATER-THAN-TOKEN, additive-expression
  | relational-expression, LESS-EQUAL-TOKEN, additive-expression
  | relational-expression, GREATER-EQUAL-TOKEN, additive-expression;
additive-expression
  = multiplicative-expression
  | additive-expression, PLUS-TOKEN, multiplicative-expression
  | additive-expression, MINUS-TOKEN, multiplicative-expression;
multiplicative-expression
  = prefix-expression
  | multiplicative-expression, ASTERISK-TOKEN, prefix-expression
  | multiplicative-expression, SLASH-TOKEN, prefix-expression
  | multiplicative-expression, PERCENT-TOKEN, prefix-expression;
prefix-expression
  = postfix-expression
  | BITWISE-NOT-TOKEN, prefix-expression
  | LOGICAL-NOT-TOKEN, prefix-expression
  | PLUS-TOKEN, prefix-expression
  | MINUS-TOKEN, prefix-expression;
postfix-expression
  = primary-expression
  | directive-call-expression;
directive-call-expression
  = identifier, group, [ block ]
  | identifier, block;
primary-expression
  = parenthesized-expression
  | UNIT-TOKEN
  | NULL-TOKEN
  | bool-literal
  | int-literal
  | float-literal
  | id-expression
  | string-literal
  | block
  | group;
parenthesized-expression
  = PARENTHESIS-LEFT-TOKEN, expression, PARENTHESIS-RIGHT-TOKEN;
bool-literal
  = TRUE-TOKEN
  | FALSE-TOKEN;
int-literal
  = BINARY-INT-TOKEN
  | OCTAL-INT-TOKEN
  | DECIMAL-INT-TOKEN
  | HEXADECIMAL-INT-TOKEN;
float-literal
  = INFINITY-TOKEN
  | DECIMAL-FLOAT-TOKEN;
id-expression
  = IDENTIFIER-TOKEN ? not followed by group or block ?;
string-literal
  = QUOTE-TOKEN, { string-literal-markup-element }, QUOTE-TOKEN;
string-literal-markup-element
  = STRING-LITERAL-TEXT-TOKEN
  | common-markup-element;
block
  = BRACE-LEFT-TOKEN, { block-markup-element }, BRACE-RIGHT-TOKEN;
block-markup-element
  = BLOCK-TEXT-TOKEN
  | common-markup-element;
