DOCUMENT
  = { DOCUMENT-MARKUP-ELEMENT };
DOCUMENT-MARKUP-ELEMENT
  = DOCUMENT-TEXT-TOKEN
  | COMMON-MARKUP-ELEMENT;
DOCUMENT-TEXT-TOKEN
  = DOCUMENT-TEXT-CHAR, { DOCUMENT-TEXT-CHAR };
DOCUMENT-TEXT-CHAR
  = ? any character ? - "\";

COMMON-MARKUP-ELEMENT
  = ESCAPE-TOKEN
  | LINE-COMMENT-TOKEN
  | BLOCK-COMMENT-TOKEN
  | DIRECTIVE-SPLICE;
ESCAPE-TOKEN
  = "\", ESCAPABLE-CHAR
  | "\", LINE-TERMINATOR;
ESCAPABLE-CHAR
  =  "{" |  "}" |  "[" |  "]" |  "(" |  ")" |  "," |  "." |  "="
  |  "!" |  '"' |  "#" |  "$" |  "%" |  "&" |  "'" |  "+" |  "/"
  |  ";" |  "<" |  ">" |  "?" |  "@" |  "^" |  "|" |  "~" |  "-"
  |   HT |   VT |   SP ;
LINE-COMMENT-TOKEN
  = "\:", { LINE-COMMENT-CHAR }, LINE-TERMINATOR;
LINE-COMMENT-CHAR
  = ? any character ? - (LF | CR);
BLOCK-COMMENT-TOKEN
  = "\*", { BLOCK-COMMENT-CHAR }, "*\";
BLOCK-COMMENT-CHAR
  = ? any character ? - ("*" ? followed by "\" ?);
DIRECTIVE-SPLICE
  = DIRECTIVE-SPLICE-NAME-TOKEN, [ GROUP ], [ BLOCK ];
DIRECTIVE-SPLICE-NAME-TOKEN
  = "\", UNQUOTED-IDENTIFIER-TOKEN;

IDENTIFIER
  = UNQUOTED-IDENTIFIER-TOKEN
  | QUOTED-IDENTIFIER-TOKEN;
UNQUOTED-IDENTIFIER-TOKEN
  = UNQUOTED-IDENTIFIER-CHAR - DIGIT, { UNQUOTED-IDENTIFIER-CHAR }
  ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
UNQUOTED-IDENTIFIER-CHAR
  = "_" | DIGIT | LETTER;
DIGIT
  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
LETTER
  = ? ASCII alphabetic character ?;
QUOTED-IDENTIFIER-TOKEN
  = "`", { QUOTED-IDENTIFIER-CHAR }, "`";
QUOTED-IDENTIFIER-CHAR
  = ? any character ? - ("`" | CR | LF);

GROUP
  = PARENTHESIS-LEFT-TOKEN, { GROUP-CONTENT }, PARENTHESIS-RIGHT-TOKEN;
PARENTHESIS-LEFT-TOKEN
  = "(";
PARENTHESIS-RIGHT-TOKEN
  = ")";
GROUP-CONTENT
  = GROUP
  | BLOCK
  | IDENTIFIER
  | QUOTED-STRING
  | FLOAT-LITERAL
  | INT-LITERAL
  | EQUALS-TOKEN
  | COMMA-TOKEN
  | ELLIPSIS-TOKEN
  | UNIT-TOKEN
  | NULL-TOKEN
  | TRUE-TOKEN
  | FALSE-TOKEN
  | BLANK;
EQUALS-TOKEN
  = "=";
COMMA-TOKEN
  = ",";
ELLIPSIS-TOKEN
  = "...";
UNIT-TOKEN
  = "unit" ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
NULL-TOKEN
  = "null" ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
TRUE-TOKEN
  = "true" ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
FALSE-TOKEN
  = "false" ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
INT-LITERAL
  = BINARY-INT-TOKEN
  | OCTAL-INT-TOKEN
  | DECIMAL-INT-TOKEN
  | HEXADECIMAL-INT-TOKEN;
BINARY-INT-TOKEN
  = [ "-" ], "0B", BINARY-DIGIT, { BINARY-DIGIT };
OCTAL-INT-TOKEN
  = [ "-" ], "0O", OCTAL-DIGIT, { OCTAL-DIGIT };
DECIMAL-INT-TOKEN
  = [ "-" ], DIGIT, { DIGIT };
HEXADECIMAL-INT-TOKEN
  = [ "-" ], "0X", HEXADECIMAL-DIGIT, { HEXADECIMAL-DIGIT };
BINARY-DIGIT
  = "0" | "1";
OCTAL-DIGIT
  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7";
HEXADECIMAL-DIGIT
  = DIGIT
  | "A" | "B" | "C" | "D" | "E" | "F"
  | "a" | "b" | "c" | "d" | "e" | "f";

FLOAT-LITERAL
  = INFINITY-TOKEN
  | NEGATIVE-INFINITY-TOKEN
  | DECIMAL-FLOAT-TOKEN;
INFINITY-TOKEN
  = "infinity" ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
NEGATIVE-INFINITY-TOKEN
  = "-infinity;" ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
DECIMAL-FLOAT-TOKEN
  = DECIMAL-FLOAT ? not followed by UNQUOTED-IDENTIFIER-CHAR ?;
DECIMAL-FLOAT
  = [ "-" ], DIGIT, { DIGIT }, ".", { DIGIT }, [ EXPONENT ]
  | [ "-" ], ".", DIGIT, { DIGIT }, [ EXPONENT ]
  | [ "-" ], DIGIT, { DIGIT }, EXPONENT;
EXPONENT
  = ("e" | "E"), [ "+" | "-" ], DIGIT, { DIGIT };

QUOTED-STRING
  = STRING-QUOTE-TOKEN, { QUOTED-STRING-MARKUP-ELEMENT }, STRING-QUOTE-TOKEN;
STRING-QUOTE-TOKEN
  = '"';
QUOTED-STRING-MARKUP-ELEMENT
  = QUOTED-STRING-TEXT-TOKEN
  | COMMON-MARKUP-ELEMENT;
QUOTED-STRING-TEXT-TOKEN
  = QUOTED-STRING-TEXT-CHAR, { QUOTED-STRING-TEXT-CHAR };
QUOTED-STRING-TEXT-CHAR
  = ? any character ? - ("\" | '"');

BLOCK
  = BRACE-LEFT-TOKEN, { BLOCK-MARKUP-ELEMENT }, BRACE-RIGHT-TOKEN;
BRACE-LEFT-TOKEN
  = "{";
BRACE-RIGHT-TOKEN
  = "}";
BLOCK-MARKUP-ELEMENT
  = BLOCK-TEXT-TOKEN
  | COMMON-MARKUP-ELEMENT;
BLOCK-TEXT-TOKEN
  = BLOCK-TEXT-ELEMENT, { BLOCK-TEXT-ELEMENT };
BLOCK-TEXT-ELEMENT
  = BLOCK-TEXT-CHAR
  | "{", { BLOCK-TEXT-ELEMENT }, "}";
BLOCK-TEXT-CHAR
  = ? any character ? - ("\" | "}");

BLANK
  = { LINE-COMMENT-TOKEN | BLOCK-COMMENT-TOKEN | WHITESPACE-TOKEN };
WHITESPACE-TOKEN
  = { HT | LF | CR | VT | SP };
LINE-TERMINATOR
  = LF
  | CR, LF
  | CR ? not followed by LF ?;
HT = ? U+0009 CHARACTER TABULATION ?;
LF = ? U+000A END OF LINE ?;
CR = ? U+000D CARRIAGE RETURN ?;
VT = ? U+000B LINE TABULATION ?;
SP = ? U+0020 SPACE ?;
