#include <algorithm>
#include <cstddef>
#include <span>

#include "cowel/util/case_transform.hpp"

using namespace std::string_view_literals;

namespace cowel {
namespace {

struct Case_Transform_Simple_Entry {
    char32_t key;
    char32_t value;
};

constexpr Case_Transform_Simple_Entry simple_upper_table[] {
#include "case_transform_simple_upper_autogenerated.cpp.txt"
};

constexpr Case_Transform_Simple_Entry simple_lower_table[] {
#include "case_transform_simple_lower_autogenerated.cpp.txt"
};

static_assert(std::ranges::is_sorted(simple_upper_table, {}, &Case_Transform_Simple_Entry::key));
static_assert(std::ranges::is_sorted(simple_lower_table, {}, &Case_Transform_Simple_Entry::key));

const Case_Transform_Simple_Entry* simple_to_upper_impl(char32_t c)
{
    const Case_Transform_Simple_Entry* const result
        = std::ranges::lower_bound(simple_upper_table, c, {}, &Case_Transform_Simple_Entry::key);
    return result == std::ranges::end(simple_upper_table) || result->key != c //
        ? nullptr
        : result;
}

constexpr const Case_Transform_Simple_Entry* simple_to_lower_impl(char32_t c)
{
    const Case_Transform_Simple_Entry* const result
        = std::ranges::lower_bound(simple_lower_table, c, {}, &Case_Transform_Simple_Entry::key);
    return result == std::ranges::end(simple_lower_table) || result->key != c //
        ? nullptr
        : result;
}

struct Case_Transform_Special_Entry {
    char32_t key;
    std::u32string_view value;
};

constexpr Case_Transform_Special_Entry special_upper_table[] {
#include "case_transform_special_upper_autogenerated.cpp.txt"
};

constexpr Case_Transform_Special_Entry special_lower_table[] {
#include "case_transform_special_lower_autogenerated.cpp.txt"
};

static_assert(std::ranges::is_sorted(special_upper_table, {}, &Case_Transform_Special_Entry::key));
static_assert(std::ranges::is_sorted(special_lower_table, {}, &Case_Transform_Special_Entry::key));

const Case_Transform_Special_Entry* special_to_upper_impl(char32_t c)
{
    const Case_Transform_Special_Entry* const result
        = std::ranges::lower_bound(special_upper_table, c, {}, &Case_Transform_Special_Entry::key);
    return result == std::ranges::end(special_upper_table) || result->key != c //
        ? nullptr
        : result;
}

const Case_Transform_Special_Entry* special_to_lower_impl(char32_t c)
{
    static_assert(std::size(special_lower_table) == 1);
    return special_lower_table->key == c ? special_lower_table : nullptr;
}

} // namespace

char32_t simple_to_upper(char32_t c)
{
    const auto* const result = simple_to_upper_impl(c);
    return result ? result->value : c;
}

char32_t simple_to_lower(char32_t c)
{
    const auto* const result = simple_to_lower_impl(c);
    return result ? result->value : c;
}

std::u32string_view unconditional_to_upper(char32_t c)
{
    if (const auto* const special = special_to_upper_impl(c); special) {
        return special->value;
    }
    if (const auto* const simple = simple_to_upper_impl(c); simple) {
        return std::u32string_view { &simple->value, 1 };
    }
    return U""sv;
}

std::u32string_view unconditional_to_lower(char32_t c)
{
    if (const auto* const special = special_to_lower_impl(c); special) {
        return special->value;
    }
    if (const auto* const simple = simple_to_lower_impl(c); simple) {
        return std::u32string_view { &simple->value, 1 };
    }
    return U""sv;
}

namespace {

/// @brief An inclusive range `[from, to]` of code points.
struct Code_Point_Range {
    char32_t from;
    char32_t to;
};

constexpr Code_Point_Range cased_ranges[] {
#include "unicode_cased_autogenerated.cpp.txt"
};

constexpr Code_Point_Range case_ignorable_ranges[] {
#include "unicode_case_ignorable_autogenerated.cpp.txt"
};

static_assert(std::ranges::is_sorted(cased_ranges, {}, &Code_Point_Range::from));
static_assert(std::ranges::is_sorted(case_ignorable_ranges, {}, &Code_Point_Range::from));

[[nodiscard]]
bool is_in_ranges(const char32_t c, const std::span<const Code_Point_Range> ranges)
{
    const auto it = std::ranges::upper_bound(ranges, c, {}, &Code_Point_Range::from);
    // return it != ranges.begin() && c <= it[-1].to;
    if (it == ranges.begin()) {
        return false;
    }
    const Code_Point_Range& range = *std::prev(it);
    return c <= range.to;
}

/// @brief Returns `true` iff `c` has the Unicode `Cased` property.
/// A character is `Cased` if it is uppercase, lowercase, or a titlecase letter
/// (see https://www.unicode.org/reports/tr44/#Cased).
bool is_cased(const char32_t c)
{
    return is_in_ranges(c, cased_ranges);
}

/// @brief Returns `true` iff `c` has the Unicode `Case_Ignorable` property.
/// Case_Ignorable characters are skipped when applying context-sensitive
/// case transformations such as the Final_Sigma rule
/// (see https://www.unicode.org/reports/tr44/#Case_Ignorable).
bool is_case_ignorable(const char32_t c)
{
    return is_in_ranges(c, case_ignorable_ranges);
}

} // namespace

std::u32string_view contextual_to_lower(const std::u32string_view str, const std::size_t pos)
{
    static constexpr auto final_sigma = U'\N{GREEK SMALL LETTER FINAL SIGMA}';

    const char32_t c = str[pos];
    if (c != final_sigma) {
        return unconditional_to_lower(c);
    }

    // Apply the Unicode Final_Sigma condition (Unicode Standard, section 3.13):
    //   Before(C): there is a Cased character before C,
    //              with only Case_Ignorable characters intervening.
    //   After(C):  there is a Cased character after C,
    //              with only Case_Ignorable characters intervening.
    // If Before(C) and not After(C), map to U+03C2 GREEK SMALL LETTER FINAL SIGMA.
    // Otherwise, map to U+03C3 GREEK SMALL LETTER SIGMA (the unconditional mapping).

    // Scan backward, skipping Case_Ignorable characters.
    const bool before_cased = [&] {
        std::size_t i = pos;
        while (i > 0) {
            --i;
            const char32_t prev = str[i];
            if (is_case_ignorable(prev)) {
                continue;
            }
            return is_cased(prev);
        }
        return false;
    }();

    if (!before_cased) {
        return unconditional_to_lower(U'\N{GREEK CAPITAL LETTER SIGMA}');
    }

    // Scan forward, skipping Case_Ignorable characters.
    const bool after_cased = [&] {
        for (std::size_t i = pos + 1; i < str.size(); ++i) {
            const char32_t next = str[i];
            if (is_case_ignorable(next)) {
                continue;
            }
            return is_cased(next);
        }
        return false;
    }();

    if (!after_cased) {
        return std::u32string_view { &final_sigma, 1 };
    }
    return unconditional_to_lower(U'\N{GREEK CAPITAL LETTER SIGMA}');
}

} // namespace cowel
