#include <algorithm>
#include <span>

#include "cowel/util/unicode_case_props.hpp"

namespace cowel {
namespace {

struct Unicode_Prop_Range {
    char32_t from;
    char32_t to;
};

constexpr Unicode_Prop_Range cased_ranges[] {
#include "unicode_cased_autogenerated.cpp.txt"
};

constexpr Unicode_Prop_Range case_ignorable_ranges[] {
#include "unicode_case_ignorable_autogenerated.cpp.txt"
};

static_assert(
    std::ranges::is_sorted(cased_ranges, {}, &Unicode_Prop_Range::from),
    "cased_ranges must be sorted by 'from'"
);
static_assert(
    std::ranges::is_sorted(case_ignorable_ranges, {}, &Unicode_Prop_Range::from),
    "case_ignorable_ranges must be sorted by 'from'"
);

[[nodiscard]]
bool is_in_ranges(const char32_t c, const std::span<const Unicode_Prop_Range> ranges)
{
    // Find the last range whose 'from' <= c using upper_bound.
    const auto it = std::ranges::upper_bound(ranges, c, {}, &Unicode_Prop_Range::from);
    if (it == ranges.begin()) {
        return false;
    }
    const Unicode_Prop_Range& range = *std::prev(it);
    return c <= range.to;
}

} // namespace

bool is_cased(const char32_t c)
{
    return is_in_ranges(c, cased_ranges);
}

bool is_case_ignorable(const char32_t c)
{
    return is_in_ranges(c, case_ignorable_ranges);
}

} // namespace cowel
